apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-deno-auth
  template:
    metadata:
      labels:
        app: ticketing-deno-auth
    spec:
      containers:
        - name: ticketing-deno-auth
          image: gumberss/ticketing-deno-auth
      #     volumeMounts:
      #       - mountPath: /deno-dir
      #         name: deno-cache
      # volumes:
      #   - name: deno-cache
      #     emptyDir: {}

          #env:
           # - name: MONGO_URI
              #value: '123'
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-srv
spec:
  selector:
    app: ticketing-deno-auth
  ports:
    - name: auth-port
      protocol: TCP
      port: 9005
      targetPort: 9005

