apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-deno-auth-mongo
  template:
    metadata:
      labels:
        app: ticketing-deno-auth-mongo
    spec:
      containers:
        - name: ticketing-deno-auth-mongo
          image: mongo
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-srv
spec:
  selector:
    app: ticketing-deno-auth-mongo
  ports:
    - name: auth-mongo-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  
    