apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: madness-buyer
    version: v1
  name: madness-buyer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madness-buyer
      version: v1
  template:
    metadata:
      labels:
        app: madness-buyer
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:      
        name: madness-buyer
        image: gumberss/madness-buyer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/live
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/ready
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: madness-buyer-srv
  labels:
    app: madness-buyer    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: madness-buyer