apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madness-stock-mongo
  template:
    metadata:
      labels:
        app: madness-stock-mongo
    spec:
      containers:
        - name: madness-stock-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: stock-mongo-srv
spec:
  selector:
    app: madness-stock-mongo
  ports:
    - name: stock-mongo-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  
    